/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.awt.CardLayout;

/**
 *
 * @author User
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        glassFishButton = new javax.swing.JButton();
        javaeeButton = new javax.swing.JButton();
        postGreButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        glassFish = new javax.swing.JLabel();
        javaEE = new javax.swing.JLabel();
        postGre = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        glassFishButton.setText("GlassFish");
        glassFishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassFishButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(glassFishButton);

        javaeeButton.setText("JavaEE");
        javaeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaeeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(javaeeButton);

        postGreButton.setText("PostgreSQL");
        postGreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postGreButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(postGreButton);

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        glassFish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glassFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/GlassFish.jpg"))); // NOI18N
        imagePanel.add(glassFish, "0");

        javaEE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaEE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/javaee.jpg"))); // NOI18N
        imagePanel.add(javaEE, "1");

        postGre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postGre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/postgre.jpg"))); // NOI18N
        imagePanel.add(postGre, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void glassFishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassFishButtonActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_glassFishButtonActionPerformed

    private void javaeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaeeButtonActionPerformed
         CardLayout cl = (CardLayout) (imagePanel.getLayout());
         cl.show(imagePanel, "1");
    }//GEN-LAST:event_javaeeButtonActionPerformed

    private void postGreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postGreButtonActionPerformed
         CardLayout cl = (CardLayout) (imagePanel.getLayout());
         cl.show(imagePanel, "2");
    }//GEN-LAST:event_postGreButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel glassFish;
    private javax.swing.JButton glassFishButton;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel javaEE;
    private javax.swing.JButton javaeeButton;
    private javax.swing.JLabel postGre;
    private javax.swing.JButton postGreButton;
    // End of variables declaration//GEN-END:variables
}
